root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/web"
bin = "tmp/main"
include_ext = ["go", "html"]
exclude_dir = ["tmp", "vendor"]
delay = 1000 # ms

[screen]
clear_on_rebuild = true